docs(health): add documentation for the health feature
SAP/neonbee pull request #141
Opened 2022-06-17 11:52 UTC by s4heid

2022-08-02 12:37 UTC, mkhazanovych approved these changes

2022-08-02 15:33 UTC, halber requested changes

2022-08-02 15:33 UTC, halber commented on docs/health.md
> +NeonBee provides an extendable API for system health monitoring. The overall health of NeonBee is determined by a set of individual health checks. These checks consist of NeonBee *built-in checks* an
```suggestion
NeonBee provides an extendable API for system health monitoring. The overall health of NeonBee is determined by a set of individual health checks. These checks consist of NeonBee *built-in checks* and *custom checks* that can be provided by a user. All built-in checks are enabled by default, but can be disabled via the `NeonBeeConfig` or in the health-check specific [config](#configuration). The results of the health check procedures are published via a health endpoint.
```

2022-08-02 15:33 UTC, halber commented on docs/health.md
> +Health check specific settings can be applied by adding config files that satisfy the follwoing criteria:
```suggestion
Health check specific settings can be applied by adding config files that satisfy the following criteria:
```

2022-08-02 15:33 UTC, halber commented on docs/health.md
> +Health checks can be configured in multiple ways. [Global settings](#global-settings-via-neonbeeconfig) apply to *all* checks and can be used to enable / disable all health checks for instance, where
```suggestion
Health checks can be configured in multiple ways. [Global settings](#global-settings-via-neonbeeconfig) apply to *all* checks and can be used to enable / disable all health checks. [Health check specific settings](#health-check-specific-settings-via-config-file-on-health-check-level) on the other hand, apply only to a *single* health check. The precedence order is always; health check specific settings overwrite the global.
```

2022-08-04 07:39 UTC, halber approved these changes
lgtm

2022-08-04 07:47 UTC, merged