feat(health): add event-loop health check
SAP/neonbee pull request #168
Opened 2022-08-16 12:52 UTC by s4heid

2022-08-29 13:37 UTC, s4heid commented on src/main/java/io/neonbee/health/EventLoopHealthCheck.java
> +                    LOGGER.info("[{}] Pending Tasks of \"{}\": {}", neonBee.getNodeId(),
should be debug

2022-08-31 09:30 UTC, pk-work requested changes

2022-08-31 09:30 UTC, pk-work commented on src/main/java/io/neonbee/health/EventLoopHealthCheck.java
> +                    LOGGER.info("[{}] Pending Tasks of \"{}\": {}", neonBee.getNodeId(),
trace

2022-08-31 10:25 UTC, s4heid commented on src/main/java/io/neonbee/health/EventLoopHealthCheck.java
> +    private static final int DEFAULT_CRITICAL_EVENTBUS_SIZE = 1;
Changed to 5. We can adapt this once we have more experience with it.

2022-08-31 10:26 UTC, s4heid commented on src/main/java/io/neonbee/health/EventLoopHealthCheck.java
> +        }
Agreed

2022-08-31 10:32 UTC, s4heid commented on src/test/java/io/neonbee/internal/verticle/HealthCheckVerticleTest.java
> -            assertThat(resp.size()).isEqualTo(1);
As discussed, this is already checked elsewhere and needs to be adapted every single time if a new health check is added. Thus, removing it.

2022-08-31 11:03 UTC, pk-work approved these changes

2022-08-31 11:08 UTC, merged