fix(health): make health check collection more resilient
SAP/neonbee pull request #185
Opened 2022-10-06 12:47 UTC by s4heid

Whenever a health check verticle did not answer, a failed future was returned by the health check registry in the attempt of collecting all health check data. Especially in the clustered case this might happen quite often due to restarts caused by a deployment, for instance. In that case an error would be reported, although all relevent data might be available.

Therefore, this change makes the data collection more resilient by respecting that some verticles might not be able to answer.

Once the de-registering of health check verticles from the shared map is available/implemented, it should be less likely that this situation happens, but still possible.

2022-10-07 12:00 UTC, halber requested changes
All good, just an unnecessary cast that can be removed.

2022-10-07 12:00 UTC, halber commented on src/main/java/io/neonbee/health/HealthCheckRegistry.java
> +                    .map(JsonObject.class::cast).peek(result -> result.remove("outcome")).collect(toList());
I don't see why we need to convert the result to a JsonObject.
```suggestion
                    .peek(result -> result.remove("outcome")).collect(toList());
``

2022-10-07 12:00 UTC, halber commented on src/main/java/io/neonbee/health/HealthCheckRegistry.java
> +                                .map(Future::result).map(JsonArray.class::cast).flatMap(JsonArray::stream)
I don't see why we need to convert the result to a JsonArray.
```suggestion
                                .map(Future::result).flatMap(JsonArray::stream)``

2022-10-07 14:04 UTC, s4heid commented
Good catch!

2022-10-10 07:12 UTC, halber approved these changes
LGTM

2022-10-10 07:54 UTC, merged