refactor: extract registry logic
SAP/neonbee pull request #216
Opened 2022-11-16 10:05 UTC by halber

There is a registry logic that is commonly used. In order to reuse this logic, I have moved this logic to a new WriteSafeRegistry class.

2022-11-21 08:32 UTC, s4heid requested changes

2022-11-21 08:32 UTC, s4heid commented on src/main/java/io/neonbee/entity/EntityVerticle.java
> +    static WriteSafeRegistry getRegistry(Vertx vertx) {
You ensure thread safety via the locking in the `WriteSafeRegistry` itself, but honestly I don't feel comfortable with this singleton approach. It comes with several other drawbacks like the fact that we need to introduce a `EntityVerticleExtension`. I would even rather manage it centrally via the NeonBee instance instead. Did you consider this?

2022-11-21 08:32 UTC, s4heid commented on src/main/java/io/neonbee/internal/WriteSafeRegistry.java
> +    public Future<Void> unregister(String sharedMapKey, String value) {
this method is completely untested. Also noticed there is no `WriteSafeRegistryTest` class; might be a good idea to introduce and write a test for `unregister`.

2022-11-21 08:32 UTC, s4heid commented on src/main/java/io/neonbee/entity/EntityVerticle.java
> +    static WriteSafeRegistry getRegistry(Vertx vertx) {
Maybe, let's have a short sync after standup to discuss available options.

2022-12-08 08:21 UTC, merged

2022-12-08 08:26 UTC, pk-work commented
Also from my side a big thank you @halber !