feat: add SelfCleaningRegistry and make Registry interface type safe
SAP/neonbee pull request #325
Opened 2023-06-01 18:10 UTC by pk-work

This change introduces a SelfCleaningRegistry. The SelfCleaningRegistry knows which values were added by which cluster node. When a node leaves the cluster, all node-related values are removed from the registry.

This change also changes the Registry interface. Now a Registry is type safe and offers supports registration of multiple values for the same key.

2023-06-05 12:21 UTC, halber requested changes

2023-06-05 12:36 UTC, pk-work commented on src/main/java/io/neonbee/entity/EntityVerticle.java
> +                stopPromise.fail(e);
Good catch

2023-06-05 12:40 UTC, pk-work commented on src/main/java/io/neonbee/NeonBee.java
> +        this.entityRegistry = new SelfCleaningRegistry<>(vertx, EntityVerticle.REGISTRY_NAME);
We can do this, but then we also have to pass the HealthCheckRegistry into the NeonBee constructor.

2023-06-05 13:36 UTC, pk-work commented on src/main/java/io/neonbee/internal/registry/SelfCleaningRegistryController.java
> +    }
We have to consider here whether we want to have a singleton or multiple instances (one per registry instance) of SelfCleaningRegistryController.

Both is fine and easy to implement. Let's have a quick poll tomorrow in the Committer Meeting.

2023-06-06 23:06 UTC, halber approved these changes
LGTM

2023-06-07 07:14 UTC, merged