refactor: move error handler configuration to ServerConfig class
SAP/neonbee pull request #60
Opened 2021-07-16 20:13 UTC by kristian

Before this change the JsonObject passed to the ServerVerticle was used to read the configuration for the custom error template to use. With this change the JsonObject was replaced by the ServerConfig object. In addition to a custom errorHandlerClassName a new errorHandlerTemplate property was added, which can be used to just specify a different (HTML) template to use in the DefaultErrorHandler.

2021-07-19 10:31 UTC, pk-work requested changes
Only typos

2021-07-19 10:31 UTC, pk-work commented on src/main/java/io/neonbee/config/ServerConfig.java
> +     * Sets the path to a error handler template to use either in the {@link DefaultErrorHandler} or in any custom error
```suggestion
     * Sets the path to an error handler template to use either in the {@link DefaultErrorHandler} or in any custom error
```

2021-07-21 07:05 UTC, kristian commented
> Only typos

Thanks for the review Pascal, I did fix the typos

2021-07-21 10:13 UTC, pk-work approved these changes

2021-07-21 10:13 UTC, merged